from uuid import UUID

LOCAL_HOST = "127.0.0.1"
DEFAULT_PORT = 1234
RESPONSE_HEADER_LENGTH = 1 + 2 + 4
REQUEST_HEADER_LENGTH = 16 + 1 + 2 + 4
KEY_LEN = 160 * 8
REQUEST_HDR_FORMAT_NO_UUID = "<BHI"
RESPONSE_HEADER_FORMAT = "<BHI"
NULL_TERMINATED = "\\"
NAME_FIELD_LEN = 255
REGISTRATION_CODE = 1100
REGISTRATION_SUCCESS_CODE = 2100
PORT_FILE_PATH = "port.info"
SERVER_VERSION = 3
UUID_LEN = 16
DATE_FORMAT = "%Y-%m-%d %H:%M"

DB_SERVER = "server.db"
CREATE_CLIENTS_TABLE_SQL = """CREATE TABLE clients(ID varchar(255) NOT NULL PRIMARY KEY, Name varchar(127) NOT NULL, PublicKey varchar(160), LastSeen Text, AESKey Blob);"""
CREATE_FILES_TABLE_SQL = """CREATE TABLE files(ID varchar(255) NOT NULL PRIMARY KEY, FileName varchar(255) NOT NULL, PathName varchar(255) NOT NULL, Verified INTEGER);"""

DEFAULT_USERNAME = "ziv"
DEFAULT_UUID = UUID('{d8e0afe7-3d73-11ed-af35-00f48dfa20f2}')
